aaly_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  knee_left_back_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: aaly__knee_left_back_joint

  # Position Controllers ---------------------------------------
  knee_left_front_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: aaly__knee_left_front_joint

  # Position Controllers ---------------------------------------
  knee_right_back_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: aaly__knee_right_back_joint

  # Position Controllers ---------------------------------------
  knee_right_front_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: aaly__knee_right_front_joint